FROM ubuntu
RUN apt update
RUN apt install -y make build-essential git wget cmake gawk libtinfo-dev libcap-dev zlib1g-dev xz-utils python3 python3-dev python3-pip
RUN wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
RUN apt install ./libtinfo5_6.3-2ubuntu0.1_amd64.deb
RUN rm libtinfo5_6.3-2ubuntu0.1_amd64.deb

RUN wget -q https://releases.llvm.org/4.0.0/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-16.10.tar.xz 
RUN tar -xf clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-16.10.tar.xz
RUN rm clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-16.10.tar.xz
RUN cp -r clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-16.10 /usr/llvm
RUN cp -r /usr/llvm/bin/* /usr/bin
RUN cp -r /usr/llvm/lib/* /usr/lib
RUN cp -r /usr/llvm/include/* /usr/include
RUN cp -r /usr/llvm/share/* /usr/share

RUN mkdir /beacon
RUN cd /beacon
WORKDIR /beacon

RUN git clone https://github.com/SVF-tools/SVF.git
WORKDIR /beacon/SVF
RUN git reset --hard 3170e83b03eefc15e5a3707e5c52dc726ffcd60a
RUN sed -i 's/LLVMRELEASE=\/home\/ysui\/llvm-4.0.0\/llvm-4.0.0.obj/LLVMRELEASE=\/usr\/llvm/' build.sh
RUN ./build.sh

ADD precondInfer /beacon/precondInfer
RUN mkdir /beacon/precondInfer/build
WORKDIR /beacon/precondInfer/build
RUN cmake \
	-DENABLE_KLEE_ASSERTS=ON \
	-DCMAKE_BUILD_TYPE=Release \
	-DLLVM_CONFIG_BINARY=/usr/bin/llvm-config \
	-DSVF_ROOT_DIR=$FUZZER/beacon/SVF \
	-DSVF_LIB_DIR=$FUZZER/beacon/SVF/Release-build/lib \
	..
RUN make -j

ADD Ins /beacon/Ins
RUN mkdir beacon/Ins/build -p
WORKDIR /beacon/Ins/build
RUN CXXFLAGS="-fno-rtti" cmake \
	-DLLVM_DIR=/usr/lib/cmake/llvm/ \
	-DCMAKE_BUILD_TYPE=Release \
	..
RUN make -j

ADD Fuzzer /beacon/Fuzzer

COPY beacon.sh /beacon/beacon.sh

RUN pip3 install wllvm --break-system-packages

ENTRYPOINT ["/bin/bash", "/beacon/beacon.sh"]
